// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';

export function AddContext(arg1:string,arg2:string):Promise<void>;

export function Certificates():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Certificate_>;

export function Contexts():Promise<Array<service.ContextInfo>>;

export function DeleteContext(arg1:string):Promise<void>;

export function Firewalls():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Firewall_>;

export function FloatingIPs():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_FloatingIP_>;

export function Init():Promise<void>;

export function LoadBalancers():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_LoadBalancer_>;

export function Networks():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Network_>;

export function SSHKeys():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_SSHKey_>;

export function Servers():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Server_>;

export function Status():Promise<main.Status>;

export function UseContext(arg1:string):Promise<void>;

export function Volumes():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Volume_>;

export function Zones():Promise<main.Listing_github_com_milosDamjanovic17_hetzner_auto_orchestrator_internal_hetzner_Zone_>;
