// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContext(arg1, arg2) {
  return window['go']['main']['App']['AddContext'](arg1, arg2);
}

export function Certificates() {
  return window['go']['main']['App']['Certificates']();
}

export function Contexts() {
  return window['go']['main']['App']['Contexts']();
}

export function DeleteContext(arg1) {
  return window['go']['main']['App']['DeleteContext'](arg1);
}

export function Firewalls() {
  return window['go']['main']['App']['Firewalls']();
}

export function FloatingIPs() {
  return window['go']['main']['App']['FloatingIPs']();
}

export function Init() {
  return window['go']['main']['App']['Init']();
}

export function LoadBalancers() {
  return window['go']['main']['App']['LoadBalancers']();
}

export function Networks() {
  return window['go']['main']['App']['Networks']();
}

export function SSHKeys() {
  return window['go']['main']['App']['SSHKeys']();
}

export function Servers() {
  return window['go']['main']['App']['Servers']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UseContext(arg1) {
  return window['go']['main']['App']['UseContext'](arg1);
}

export function Volumes() {
  return window['go']['main']['App']['Volumes']();
}

export function Zones() {
  return window['go']['main']['App']['Zones']();
}
