// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Contexts() {
  return window['go']['main']['App']['Contexts']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
