// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';

export function Contexts():Promise<Array<service.ContextInfo>>;

export function Status():Promise<main.Status>;
